---
inherit_from:
  - .niftany/layout.yml
  - .niftany/lint.yml
  - .niftany/metrics.yml
  - .niftany/naming.yml
  - .niftany/niftany_rubocop_rspec.yml
  - .niftany/performance.yml
  - .niftany/style.yml
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  NewCops: enable

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/lib/psulib_traject/workers/base_spec.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/lib/psulib_traject/workers/base_spec.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'spec/lib/psulib_traject/workers/base_spec.rb'
