---
inherit_from:
  - .niftany/layout.yml
  - .niftany/lint.yml
  - .niftany/metrics.yml
  - .niftany/naming.yml
  - .niftany/niftany_rubocop_rspec.yml
  - .niftany/performance.yml
  - .niftany/style.yml
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'config/ignorethis_*.rb'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/lib/psulib_traject/workers/base_spec.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/lib/psulib_traject/workers/base_spec.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'spec/lib/psulib_traject/workers/base_spec.rb'

Lint/MissingSuper:
  Exclude:
    - 'lib/psulib_traject/processors/call_number/dewey.rb'
    - 'lib/psulib_traject/processors/call_number/lc.rb'
    - 'lib/psulib_traject/processors/call_number/other.rb'
    - 'lib/psulib_traject/null_object.rb'

Lint/MixedRegexpCaptureTypes:
  Exclude:
    - 'lib/psulib_traject/processors/call_number/lc.rb'
    - 'lib/psulib_traject/processors/call_number/dewey.rb'

RSpec/ImplicitSubject:
  Exclude:
    - 'spec/lib/psulib_traject/macros/subjects_spec.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/lib/psulib_traject/processors/call_number/lc_spec.rb'
    - 'spec/lib/psulib_traject/processors/call_number/dewey_spec.rb'

RSpec/ExpectActual:
  Exclude:
    - 'spec/lib/psulib_traject/processors/call_number/lc_spec.rb'
    - 'spec/lib/psulib_traject/processors/call_number/dewey_spec.rb'
