---
#No collection alias in local dev
solr_url: http://localhost:8983/solr/
collection_name: psul_blacklight
log_batch_size: 100_000
solr_version: 7.4.0
log_file: log/traject.log
log_error_file: log/traject_error.log
solr_writer_commit_on_close: true
reader_class_name: Traject::MarcCombiningReader
marc4j_reader_permissive: true
marc4j_reader_source_encoding: UTF-8